name = "PulseAudioBuilder"
uuid = "8b453478-1b9f-11e9-2ded-8beed674bb7c"
authors = ["YuK_Ota <whitenightwinter@gmail.com>"]
version = "0.1.0"

[deps]
BinaryBuilder = "12aac903-9f7c-5d81-afc2-d9565ea332ae"
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
